Make flake8 tests fail the test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -34,8 +34,18 @@ jobs:
       run: |
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        # Save exit code into variable
+        retVal=$?
+        if [ $retVal -ne 0 ]; then
+            exit $retVal
+        fi
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+        # Save exit code into variable
+        retVal=$?
+        if [ $retVal -ne 0 ]; then
+            exit $retVal
+        fi
     - name: Setup env for tests
       run: |
         git config --global user.email "you@example.com"
